### ISSUE TITLE
Replace old Camunda BPMN repository 

### ISSUE THREAD

**Issue by wederbn** [OpenTOSCA/camunda-engine#1]
- [x] Add Github workflow to build image based on this repository
- [x] Archive old repository available [here](https://github.com/OpenTOSCA/camunda-bpmn)
- [ ] Add first release comprising new engine
- [ ] Update documentation (?)

**Comment by nyuuyn** [comment]
Can we add the history scripts maybe as a git submodule ? To enable fetching latest changes in an easy way?

**Comment by wederbn** [comment]
In principle yes, however, Camunda changed the plugin mechanism between version 7.14 and 7.15 (as far as I remember) and I had some trouble integrating the latest version of the scripts. But would be a nice improvement, so feel free to try it out :-)
